--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jojoe77777/FormAPI
branches:
  - master
projects:
  libLanguageSystem:
    path: ""
    type: library
    model: virion
    libs:
      - src: AID-LEARNING/FormAPI/libFormAPI
        version: ^2.1.0
      - src: AID-LEARNING/IconForm/libIconForm
        version: ^1.0.0
...
